### ISSUE TITLE
Moving django-cachalot

### ISSUE THREAD

**Issue by BertrandBordage** [jazzband-roadies/help#172]
Hi dear roadies & other Jazzband members!

I created a rather well-known project called [django-cachalot](https://github.com/noripyt/django-cachalot) 5 years ago. Unfortunately I no longer have time to maintain it. In fact I very rarely used it since late 2015. I maintained it just because I liked the project and it wasn’t too hard to maintain.

It is still rather simple to maintain, but I really no longer have the time nor the motivation to do that on a project I didn’t install once in the past 12 months.

If that’s OK with everyone, I would like to move this project to Jazzband, so that I don’t become a blocker to people that still use django-cachalot.

There are often contributors submitting PRs to add support for newer Django versions. Often these PRs are too naïve and don’t add tests for new Django ORM features. It requires to go through the release notes and the commit history to reverse engineer ORM changes.

So if this project joins Jazzband, I honestly think it is likely to become a little less bulletproof than what I tried to make it for every new Django release. At least when the contributions start arriving. That’s what I felt with Django debug toolbar that is now more stable than when it joined Jazzband.

So if you could up/down vote this post, it would be great :) I will move the repo to Jazzband in a week if there is no argument against it.

**Comment by jezdez** [comment]
Hi @BertrandBordage, Jazzband founder and roadie here, please don't do this: `I will move the repo to Jazzband in a week if there is no argument against it.` While it may look like it's no work, adding repos and making sure they continue to be maintained is non-zero work. I'm glad you opened a ticket, but this is just the start of a discussion, and you can't assume that your project is a viable candidate for Jazzband.

Now, since you've framed your question about moving it to Jazzband in a way that makes me think that you want to step away from the project right away and the non-trivial nature of the project (I've used cache-machine and cachops for a few years), please let me know who are regular contributors to the project so we can ask them to become projects leads under the Jazzband. Otherwise I'm a bit hesitant to be honest about the long-term viability of it.

**Comment by BertrandBordage** [comment]
Thanks for your reply @jezdez! I perfectly understand and will not move the repository unless you allow it.
The project doesn’t have regular contributors apart from me, as you can see here: https://github.com/noripyt/django-cachalot/graphs/contributors
@fabiocaccamo seemed particularly interested to see the project join Jazzband, but I don’t know if he would be interested in becoming the lead developer on django-cachalot.

**Comment by fabiocaccamo** [comment]
@BertrandBordage I asked to move the project to Jazzband in the hope that someone would keep it updated.
I would like to be the lead developer, but I don't have the time to follow this project as well.
I'm pretty sure that on Jazzband the project will be kept up to date.

**Comment by jezdez** [comment]
@BertrandBordage Okay, one of the viability questions I usually ask is: "Will a project be maintained going forward once moved to Jazzband?", and since you've specifically said that you don't have time anymore I'm not super sure this is the right fit. I'd like to encourage you to reach out to its users more and find someone able to do the low-level maintenance needed to keep it afloat.

Libraries.io has a great section about usage, that could be a good starting point to reach out to: https://libraries.io/pypi/django-cachalot/usage

@fabiocaccamo It's not fair to hope for the Jazzband members to take on a project where the ongoing maintenance is unclear. Since you don't have a history of maintaining the project yourself (looking at the commit history, please correct me if I'm wrong), I'm afraid that becoming the lead developer isn't an option either since contribution history is the measure for me to gauge your ability to maintain it going forward. Doing code-reviews, updating the documentation, preparing releases is all something that would be in the wheelhouse of a lead developer.

**Comment by fabiocaccamo** [comment]
@jezdez sorry, I misunderstood the purpose of JazzBand, I read it on the website well and now it is clear to me. As said, I'm not interested to become the lead developer of this project.

**Comment by BertrandBordage** [comment]
OK, so let’s close this then. I will give merge permissions to some users instead.
Thank you for your time @jezdez! And your work, we see you everywhere in the Django community :o

**Comment by jezdez** [comment]
@BertrandBordage No problem, I'm glad you asked! Please don't hesitate to reopen this when you've found someone who is willing to project lead this here in Jazzband, the decision isn't set in stone and we can always find a way forward under better circumstances.

**Comment by jezdez** [comment]
@fabiocaccamo Thank you elaborating, I appreciate the clarity. We're here in case you change your mind in the future or someone else steps up. 🙌
