### ISSUE TITLE
[Django-pipeline][Travis] Invalid or non-existent authentication information

### ISSUE THREAD

**Issue by TheBuky** [jazzband-roadies/help#177]
I participate to [Django-pipeline](https://github.com/jazzband/django-pipeline/), who is member of [jazzband](https://jazzband.co/about). 
But after pushing my modifications and successfully passed the tests, Travis fails to publish the package on PyPI for the reason: `HTTPError: 403 Client Error: Invalid or non-existent authentication information. for url: https://upload.pypi.org/legacy/` cf. related [issue](https://github.com/jazzband/django-pipeline/issues/705) and [travis job](https://travis-ci.org/jazzband/django-pipeline/jobs/629717022)

Makes it possible the confirm the information given in `travis.yml` to automatically publish packages with [Jazzband Bot](https://pypi.org/user/jazzband/) on PyPI? And if they are wrong generate new `password / secret` and save it in the project.

Thank you

**Comment by cyberdelia** [comment]
I believe this is due to me enabling 2FA on my Pypi account. I tried to switch to [Pypi token authentication](https://docs-staging.travis-ci.com/user/deployment/pypi/), but I ran into [this issue](https://travis-ci.community/t/travis-encrypt-data-too-large-for-pypi-tokens-with-older-repos/5792/2) while trying to encrypt the token.

We might be able switch to Github Actions, but only a roady can access settings for the repository to set the token, so we're stuck.

**Comment by camilonova** [comment]
@jezdez can you help us?

**Comment by TheBuky** [comment]
Hey @jezdez, can you please help us to uresolv the problem? Thank.

**Comment by jezdez** [comment]
Hey there, sure thing, I've just enabled auto-releases via the [Jazzband package index](https://jazzband.co/about/releases) and made @cyberdelia the dedicated project lead to confirm the releases.

@cyberdelia could you please re-login on https://jazzband.co to sync your email addresses please? Once a release has happened an email will be sent out to you to confirm the release.

**Comment by cyberdelia** [comment]
@jezdez Done!

**Comment by TheBuky** [comment]
I confirm v2.0.5 automatically publish on pypi.org.
Thank @jezdez
