### ISSUE TITLE
Django-silk PyPI issues

### ISSUE THREAD

**Issue by nasirhjafri** [jazzband-roadies/help#179]
Hi @jezdez , While preparing django silk release 4.0.0, circle CI tests failed while trying to upload to PyPI. Same happened during last two releases and I got response after weeks from the maintainers. Can you please make me a maintainer on PyPI/github for django-silk so that I can do smooth releases in future?
Thanks,

**Comment by mbeacom** [comment]
@nasirhjafri I would have tried to help resolve the issue, but I don't have access either.  It's too bad publish/maintainer access is a typical bottleneck in many jazzband projects.

**Comment by nasirhjafri** [comment]
@mbeacom yep, that's why I've requested for the maintainer access. I'm facing PyPI related issues in every release. Thanks anyhow for responding.

**Comment by jezdez** [comment]
So there are two things in play here:

1) The technical release issues are about a missing condition in the deploy section of the Travis config, which leads to a apparently broken build since Travis changed the behavior for failed deploys in the recent past. Previously this  was not visible. 

As a reminder, we're doing release to the Jazzband package index first so that the project lead @avelis can verify the release and confirm the push to PyPI. This is needed for security reasons, as you can imagine. Direct access to PyPI for Jazzband projects is prohibited for the same reason.

I'll deal with the misconfigured build setup in a separate PR (or maybe @aleksihakli?) and maybe also use a simpler test set using tox-travis.

2) Regarding the maintenance problem, if the project lead for django-silk @avelis is responding slowly to release notifications, we'll have to ask them whether they need help with the project leadership. Ideally we would extend the number of project leads, but it's up to @avelis to decide who that is.

@nasirhjafri Could you please confirm that you're volunteering to become another project lead for django-silk?

**Comment by nasirhjafri** [comment]
Hi @jezdez yes that would be better. I volunteer for django-silk project lead role. Thanks.

**Comment by avelis** [comment]
@jezdez @nasirhjafri @mbeacom I absolutely need help with project leadership. I moved this it Jazzband to get that help. If anyone else has continued time to make releases go out I gladly accept it.

**Comment by nasirhjafri** [comment]
@avelis I've been doing fixes, reviewing prs preparing releases for past few months. I would like to accept project leadership responsibility too so that I can be of more help. Thanks for responding back.

**Comment by avelis** [comment]
@nasirhjafri I have seen great things! I am glad the project has continued on!

**Comment by jezdez** [comment]
@avelis Excellent, thank you for responding and your openness to increasing the number of project leads.

@nasirhjafri Congratulations and thank you for volunteering! 🚀

See https://jazzband.co/projects/django-silk for the releases, past and future. As always, please let me know if you need any help. Please make sure you've read and understood the Jazzband [guidelines](https://jazzband.co/about/guidelines), [FAQ](https://jazzband.co/about/faq) and [release procedures](https://jazzband.co/about/releases).

Regarding the 4.0 release, I'll reply in the other ticket about an issue I found regarding the packaging setup we'll need to fix before doing the actual 4.0 release. I'm closing this for now.

**Comment by aleksihakli** [comment]
I'll see about fixing the packaging setup, I have some time available today for setting up tox-travis and correct release conditions.
