### ISSUE TITLE
Pypi uploading is not working from Travis

### ISSUE THREAD

**Issue by camilonova** [jazzband-roadies/help#182]
An error appears when a this new release was made:

https://travis-ci.org/jazzband/sorl-thumbnail/jobs/633932161

```
Authenticated as jazzband
dpl.2
Preparing deploy
dpl.3
Deploying application
sorl/__pycache__/__init__.cpython-36.pyc already exists, no checkout
Could not restore untracked files from stash entry
PyPI upload failed.
failed to deploy
```

The same version is not here: https://pypi.org/project/sorl-thumbnail/#history

This is the release: https://github.com/jazzband/sorl-thumbnail/releases/tag/12.6.0

**Comment by submarcos** [comment]
I suggest you to delete bdist_wheel part of travis deploy job

Delete 'distribution' option : https://github.com/jazzband/sorl-thumbnail/blob/master/.travis.yml#L133
Or setup for sdist only

(like in https://github.com/jazzband/django-constance/blob/master/.travis.yml)

**Comment by jezdez** [comment]
@camilonova Aha, that's not an actual the way you describe it, but the fact that all test runs of https://travis-ci.org/jazzband/sorl-thumbnail/builds/633932160 are trying to deploy since there is not limiting condition in the deploy section.

Take a look at the one in [constance's config file](https://github.com/jazzband/django-constance/blob/master/.travis.yml#L20) where it only runs on the Python 3.6 test environment, but there isn't any condition in sorl-thumbnail's other than it should only deploy on tags: https://github.com/jazzband/sorl-thumbnail/blob/13bedfb7d2970809eda597e3ef79318a6fa80ac2/.travis.yml#L136-L138

So this is an obvious bug in the config fixed by specifying one of the TOX_ENV envrionemtsn as a condition so the deploy happens only once.

To be clear: one of the runs in https://travis-ci.org/jazzband/sorl-thumbnail/builds/633932160 *did*the deploy to the Jazzband site, and you should have gotten the email about it. See https://jazzband.co/projects/sorl-thumbnail#12.6.0

There is **no** need to removed the bdist_wheel option.

**Comment by aleksihakli** [comment]
@jezdez @camilonova this has been fixed in the jazzband/sorl-thumbnail repository PR which is waiting for reviews and upstreaming :)

**Comment by jezdez** [comment]
Closing since this should be much better with https://github.com/jazzband/sorl-thumbnail/pull/610.

**Comment by benjaoming** [comment]
What needs to happen to projects that didn't have PyPi releases done before this update? Should the latest release tag be deleted and re-applied on the new commit to trigger a correct deployment (upload) ?

**Comment by aleksihakli** [comment]
@benjaoming the release can be remade by making a manual release to PyPI, but it's probably best to make a new tag and release through the automation pipeline since that doesn't hurt anyone and verifies the correct process.

**Comment by aleksihakli** [comment]
@jezdez is it possible to add permissions for me for the sorl-thumbnail GitHub repository and Jazzband site, assuming it is OK with @camilonova and other active maintainers?

I can help with making new releases and maintaining the project repository, but at the moment I can neither upstream maintenance patches nor upload versions from PyPI site so baking a proper release is a pretty big pain. We're currently doing the 3rd iteration to release 12.6.2 after failed version 12.6.1 and 12.6.0 due to rST syntax errors and project parameters.

I'm already maintaining a couple of other projects in Jazzband and believe that I can help with providing best-practices maintenance help for the contributors :)

**Comment by camilonova** [comment]
@jezdez I agree
