### ISSUE TITLE
Proposal: django-payments

### ISSUE THREAD

**Issue by patrys** [jazzband-roadies/help#203]
# Project Proposal

## Project Details
https://github.com/mirumee/django-payments

## Project Description
Django Payments is a unified API for integrating PSP (payment service provider) gateways with Django projects.

## Project Leads
@WhyNotHugo

## Confirmation of Guidelines

Please confirm the following:

- [x] I am the project owner, or have permission from the project owner, to request a transfer.

- [x] This project is a [viable candidate](https://jazzband.co/about/guidelines#viability) for Jazzband.

- [ ] This project fulfills the [documentation requirements](https://jazzband.co/about/guidelines#documentation).

- [x] This project is [tested](https://jazzband.co/about/guidelines#tests).

- [x] I am happy to adopt Jazzband's [code of conduct](https://jazzband.co/about/guidelines#conduct) in this project.

- [x] I am happy to include Jazzband's [contributing guidelines](https://jazzband.co/about/guidelines#contributing-guidelines) in this project.

**Comment by WhyNotHugo** [comment]
I'd like to chime to clarify I'm currently working on minor improvements for this project and am willing to continue maintaining it.

Since I've moved some production projects with steady sales rely on it already (as of last weekend), it's unlikely I'll stop working on it.

Interest for it seems to have been consistent over the year too.

Docs actually _do_ exist. I've some stashed changes locally to improve this further too.

Notes: handoff for rtd and pypi should also be handled.

Thanks all!

**Comment by jezdez** [comment]
@patrys Thanks, this seems indeed great, and already has some docs which just need to be extended a bit. Feel free to join Jazzband on https://jazzband.co/join and then transfer the repo using [GitHub's regular transfer functionality](https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/transferring-a-repository). A ticket to track the specific TODOs will be automatically created after the transfer.

@WhyNotHugo I'm glad to hear that you have some documentation updates in planned, which would solve the documentation requirements.

**Comment by jezdez** [comment]
The TODO issue is https://github.com/jazzband/django-payments/issues/228

**Comment by jezdez** [comment]
This is done.
