### ISSUE TITLE
I can no longer approve my PRs for django-payments

### ISSUE THREAD

**Issue by WhyNotHugo** [jazzband-roadies/help#329]
As of a few weeks ago, I can no longer approve my PRs for django-payments.

I'm really the only maintainer active, so there's nobody else that'll approve them for me, and I can't merge without an approval.

Can you tweak the rules for this project so I can merge PRs? Currently https://github.com/jazzband/django-payments/pull/340/ is blocking a minor release.

**Comment by hugovk** [comment]
I don't think it's ever been possible to *approve* your own PRs.

And by default you can *merge* your own PRs without approval, but looks like this repo has been set to require reviews before merge.

https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/approving-a-pull-request-with-required-reviews

@jezdez Please can you check the settings?

In the meantime, I've approved that PR so it can merged.

**Comment by WhyNotHugo** [comment]
@jezdez Can you have a look a this one?

I've merged a PR onto `main` locally, but I can't push to the `main` branch due to these restrictions.

**Comment by WhyNotHugo** [comment]
I think that what changed is that previously I could merge patches without an approval, and now I need an approval.

Now I can't, and being the main developer of this projects, it's becoming a pain that I can't merge thing to the main branch.

**Comment by jezdez** [comment]
I just disabled the requirement for "at least one review on pull requests". But I strongly suggest keeping the requirement for PRs, since it fosters a community effort to review code changes (pushing to main is an anti-pattern for community projects), remember that there are ~1500 Jazzband members that all can review PRs.

There is also the @jazzband/django-payments team that you can assign for review. See the current three members (@ojengwa, @mariofix, @leodarkseid) that will be notified when you do that.

<img width="440" alt="CleanShot 2023-05-30 at 22 31 06@2x" src="https://github.com/jazzband/help/assets/1610/7e013758-293f-46c6-af29-d2f364ad1e0c">
