### ISSUE TITLE
PyPI Release: pip-tools

### ISSUE THREAD

**Issue by felipecwb** [jazzband-roadies/help#341]
# PyPI Release

Can you release the `pip-tools==6.14.0` please
reference: https://github.com/jazzband/pip-tools/pull/1892

**Comment by hugovk** [comment]
The release is triggered by publishing a release:

https://github.com/jazzband/pip-tools/blob/ce2b4d9c72059cee99a0f49e649d2666ed75fd7a/.github/workflows/release.yml#L37-L43

The last one was 6.13.0 two months ago:

https://github.com/jazzband/pip-tools/actions/workflows/release.yml?query=event%3Arelease

To publish, edit the release draft at https://github.com/jazzband/pip-tools/releases and click "Publish release".

But the draft release is 7.0.0 due to an apparently backwards incompatible change (https://github.com/jazzband/pip-tools/pull/1863), whereas https://github.com/jazzband/pip-tools/pull/1892 is 6.14.0.

So make sure to decide on a consistent version number first.

Once the release is published, it will upload the artifacts to the Jazzband staging area. From there, a project lead, such as @atugushev, can release it to PyPI.

**Comment by atugushev** [comment]
Thanks for the ping! FTR: release is blocked by https://github.com/jazzband/pip-tools/pull/1863#issuecomment-1613304891.

**Comment by jezdez** [comment]
Seems like the project lead is on top of this, closing.

**Comment by atugushev** [comment]
FTR: pip-tools v6.14.0 is released.
