### ISSUE TITLE
GeoJSON Read the Docs not looking right

### ISSUE THREAD

**Issue by rayrrr** [jazzband-roadies/help#349]
The GeoJSON docs on Read the Docs do not look right. See issue reported at https://github.com/jazzband/geojson/issues/224

And see the actual page here: https://geojson.readthedocs.io/en/latest

Issues:

1) Search returns empty results page no matter the input
2) Version chooser is not functioning, only docs for latest version can be accessed
3) Generally has a 20th-century appearance compared to docs for well-configured Jazzband packages such as https://tablib.readthedocs.io

Should I follow the generic Read the Docs getting started tutorial and follow the instructions to the best of my ability, or do we have another preferred approach for Jazzband projects that I should follow, or should this be a roadie task?

**Comment by blaisep** [comment]
@rayrrr , 
### good news, 
- The  is obvious
- The fix is easy

### bad news
The Sphinx config is missing a conf.py which is the file that puts everything together. 
I could suggest that you fix this yourself, but that would be cruel. 
Since there seem to be some changes in the project's history, could you find the most recent conf.py and show it to me? If we can find a known good conf.py, I bet we can get this working in less than an hour.

**Comment by jjimenezshaw** [comment]
In case it helps, PROJ uses this conf.py file: https://github.com/OSGeo/PROJ/blob/master/docs/source/conf.py
PROJ also uses readthedocs: https://proj.org

**Comment by rayrrr** [comment]
Thanks for the advice, folks. I implemented a solution from scratch using `sphinx-quickstart` and the docs are now functioning.
