### ISSUE TITLE
django-minio-storage

### ISSUE THREAD

**Issue by thomasf** [jazzband-roadies/help#65]
Hi there.. 

The plans for moving https://github.com/tomhoule/django-minio-storage/ into jazzband maintainence has advanced..

 I suggested to the original author in an e-mail conversation that he will transfer his repository to the jazzband org after which I can push all changes which I've made at https://github.com/py-pa/django-minio-storage and manually transfer any issues or other repository meta data which needs to be adjusted...

I don't want to burden the original author with having to do stuff to get this working, can we arrange so that he can transfer the repo without being a jazzband member? I told him that I will contact him again when the transfer is decided to be done.

Also, any comments on the current state of https://github.com/py-pa/django-minio-storage are welcome regarding  jazzband guidelines adherence.

**Comment by thomasf** [comment]
I just got a new idea.. If he added me as co owner of his github project I can maybe move it to jazzband myself since I'm a member? I'm not familiar with how those premissions works outside of github orgs or with jazzband.

**Comment by jezdez** [comment]
@thomasf Sorry for the delay in getting back to you.

I'm not completely following your request, lemme try to summarize:

1. the original author was okay with the move, but had no time
2. you forked it and made updates and wanted to apply those to the original project
3. you proposed to move the original project to the jazzband to be able to push your updates to the project
4. since opening this ticket you've actually taken over the original project and maintain it under the "py-pa" organization

Does that sound right?

If you're still interested in moving the project to the Jazzband, I don't see any glaring issues with the current project and it seems useful. If that's the case, just use the GitHub repo transfer feature. Once transferred the jazzband bot will automatically create a ticket with a todo list to match the guidelines.

**Comment by thomasf** [comment]
yes, that sums it up correctly.. I have few things to do for the next release version of the package.  I'll take care of transferring the project to jazzband after the next release.

**Comment by jezdez** [comment]
@thomasf Excellent!

**Comment by jezdez** [comment]
@thomasf Hey Thomas, just checking in if this is still something you'd like to do?

**Comment by thomasf** [comment]
> @thomasf Hey Thomas, just checking in if this is still something you'd like to do?

 I am fine maintaining it myself for now, got out of some other projects so I have more time for it now.

If circumstances changes again I'll might reopen this issue.

**Comment by jezdez** [comment]
> > @thomasf Hey Thomas, just checking in if this is still something you'd like to do?
> 
> I am fine maintaining it myself for now, got out of some other projects so I have more time for it now.
> 
> If circumstances changes again I'll might reopen this issue.

Excellent, that is good news. Thank you!
